---
title: "Mapping Routes"
author: "Jesse Lecy"
output:
  html_document:
    keep_md: true
    df_print: paged
    theme: cerulean
    highlight: haddock
    toc: yes
    toc_float: yes
---


## Setup

```{r setup, include=TRUE}

knitr::opts_chunk$set(echo = TRUE, warning=F, message=F, fig.width=10)

```

```{r}
library( ggmap )
```



# BUILD BIKE STATION DATABASE

```{r}

dat <- readRDS(gzcon(url("https://github.com/lecy/CityBikeNYC/raw/master/DATA/bikes.rds")))

keep.these.vars <- c("start.station.id","start.station.name","start.station.latitude","start.station.longitude")

stations <- unique( dat[ keep.these.vars ] )

nrow( stations )

names( stations ) <- c("ID","StationName","LAT","LON")

stations <- stations[ order( stations$ID ) , ]

rownames( stations ) <- NULL

head( stations )


```



# Create Four Routes

```{r}



routes <- list()

for( i in 2:5 )
{

   rt <- route( from=c(stations$LON[1], stations$LAT[1]), 
             to=c(stations$LON[i], stations$LAT[i]), 
             mode="bicycling",
             structure="route" )
   
   route.name <- paste( "S.", stations$ID[1], "_to_S.", stations$ID[i], sep="" )

   rt <- cbind( rt, from.to=route.name )

   routes[[i]] <- rt

   names(routes)[i] <- route.name

}

df <- do.call( rbind.data.frame, routes )


head( df )




qmplot( lon, lat, data = df, maptype = "toner-lite",
        colour="red" ) + 
  
        geom_path(  aes( x=lon , y=lat), 
            colour="red", data=df, alpha=1, size=1 ) +
  
        facet_wrap( ~ from.to ) +
  
        theme( legend.position="none", aspect.ratio=8/6 ) 


```



# Plotting All Routes Together

The challenge here is overlaying many routes on top of each other. 


```{r, fig.width=10, fig.height=10}


routes <- list()

for( i in 2:20 )
{

   rt <- route( from=c(stations$LON[1], stations$LAT[1]), 
             to=c(stations$LON[i], stations$LAT[i]), 
             mode="bicycling",
             structure="route" )
   
   route.name <- paste( "S.", stations$ID[1], "_to_S.", stations$ID[i], sep="" )

   rt <- cbind( rt, from.to=route.name )

   routes[[i]] <- rt

   names(routes)[i] <- route.name

}

df <- do.call( rbind.data.frame, routes )

unique.routes <- unique( df$from.to )

route.frequency <- data.frame( route=unique.routes, 
                               trips=sample(1:50, length(unique.routes) ) )

head( route.frequency )

df <- merge( df, route.frequency, by.x="from.to", by.y="route" )

nyc <- qmap( "New York City, NY", color='bw', zoom=13 )  

nyc +  geom_path(  aes( x=lon , y=lat, group=from.to ), 
            colour="#1E2B6A", data=df, alpha=0.5, size=df$trips/25 )



```









```{css}
p {
color: black;
margin: 0 0 20px 0;
}

td {
    padding: 3px 10px 3px 10px;
    text-align: center;
}

table
{ 
    margin-left: auto;
    margin-right: auto;
    margin-top:80px;
    margin-bottom:100px;
}

h1, h2{
  margin-top:100px;
  margin-bottom:20px;
}

H5{
    text-align: center;
    color: gray;
    font-size:0.8em;
}

img {
    max-width: 90%;
    display: block;
    margin-right: auto;
    margin-left: auto;
    margin-top:30px;
    margin-bottom:20px;
}

pre {
  overflow-x: auto;
}

pre code {
   display: block; 
   padding: 0.5em;
   margin-bottom:20px;
}

code {
  font-size: 92%;
  border: 10px solid #F8F8F8;
  margin-bottom: 2px;
}

code[class] {
  background-color: #F8F8F8;
}

```

